# Generated by Django 6.0.5 on 2026-05-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="acknowledged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="is_acknowledged",
            field=models.BooleanField(default=False),
        ),
    ]
