# Generated by Django 5.2.14 on 2026-06-03 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_pulsesession_incident_last_verified_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="location_accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="incident",
            name="reporter_type",
            field=models.CharField(
                blank=True,
                choices=[("victim", "Victim"), ("bystander", "Bystander")],
                default="bystander",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trustedcontact",
            name="contact_gender",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="incident",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="ngocontact",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="pulsesession",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="trustedcontact",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="trustedcontact",
            name="relationship",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
