# Generated by Django 6.0.5 on 2026-05-10 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0002_incident_acknowledged_at_incident_is_acknowledged"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incident",
            options={"ordering": ["-incident_date", "-incident_time"]},
        ),
    ]
