# Generated by Django 5.2.14 on 2026-06-03 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incidents", "0003_incident_latitude_incident_location_accuracy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="reporter_type",
            field=models.CharField(
                blank=True,
                choices=[("victim", "Victim"), ("bystander", "Bystander")],
                default="victim",
                max_length=20,
            ),
        ),
    ]
